# Generated by Django 5.2.1 on 2025-05-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_teacher_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="Date_of_Birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="Gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="Grade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
